### ISSUE TITLE
"Event Edit" / "Event Create" page for organizer

### ISSUE THREAD

**Issue by sueszli** [matchyOrg/matchy#17]
Todo:

- [ ] Add label to use-group switch
- [x] Only show relevant fields depending on action
- [x] Add actual inputs for date and time
- [ ] Add logic to event-edit page
- [ ] Add client-side validation
- [ ] Improve styling
- [ ] Improve error handling

**Comment by stefnotch** [comment]
What stuff needs to be done here?
