### ISSUE TITLE
Race condition in router

### ISSUE THREAD

**Issue by sueszli** [matchyOrg/matchy#20]
Currently we have multiple routes which require fully registered users. Since we have to fetch the profile of users to check if they fully registered there's always a delay between when the route-guard is activated and when we actually know whether the user is fully registered or not.

This is easily seen when navigating to a page that requires a fully completed profile and then refreshing the page. This will redirect the user to the profile edit page whether they have completed their profile or not.

There's two ways to prevent this:
- Wait for profile to be loaded before proceeding with routing.
- Removing the "fully registered"-guards and instead have validation when an action happens that requires the profile.

I personally prefer option 2, because there's really no need to not let users without a fully completed profile go to certain routes. We can still check if they're fully registered if they, for example, try to create an event and if they're not, we could have a popup where they insert their name. There's also the fact that the route-guards don't prevent anyone from accessing the routes and there's nothing stopping them from actually creating events when they are not fully registered.

**Comment by sueszli** [comment]
As per @stefnotch 's suggestion we should save the profile in localstorage. That way we do not have to fetch it from the database and would eliminate the race condition.

We should figure out when it is necessary to refetch the profile or if we should refetch the profile occasionally, since users might change their profile info on another device which would make the localstorage stale.

We should also consider the possibility that users may delete localstorage which would reintroduce the race condition for them.

**Comment by MJDeligan** [comment]
As a test I implemented this using localstorage and it works, but it still doesn't feel good. The biggest problem is that we can't trust the data in localstorage to be up to date, so there needs to be some kind of expiration date after which the profile has to be refetched and when that happens this solution does not work. 

I think the best way to handle this and keep our current login/sigin flow is to remove the "registered" routeguards and only prompt the user to set their full name once they want to take an action that actually requires the registered status.

**Comment by sueszli** [comment]
Hehe: but we can easily set stuff to expire

https://www.sohamkamani.com/javascript/localstorage-with-ttl-expiry/

**Comment by MJDeligan** [comment]
The problem isn't making it expire, it's that if it expires, localstorage doesn't help because we have to refetch anyways, which reintroduces the race condition.

**Comment by MJDeligan** [comment]
Maybe we should just not care about the full name?

We could have a reminder somewhere that informs the user that they haven't set their name yet and have them decide whether they're going to set it or not.

Ultimately it's not like it breaks the functionality of the site. The only time we ever show the name is in the matches and there's still nothing stopping anyone from just putting a random name if they want to. If someone hasn't set a name we could just display them as "Anonymous" or something.

Constantly redirecting users and being vulnerable to race conditions is way worse than someone being displayed as Anonymous because they couldn't be bothered to change their profile when prompted.

**Comment by sueszli** [comment]
Yeah you're right - this seems like a REALLY great solution.

We want to create value for the user and not force some super useless features into the app that make it janky asf

**Comment by sueszli** [comment]
Time to yeet out the entire "registered" part of the routing if it messes up the applications state management.

I'm in favor of having as little states as possible, even if it comes at the cost of sending slightly more requests to the server because the reliability of the app should come first if the performance gains with these tricks are so minimal.

**Comment by stefnotch** [comment]
Is this completed?

**Comment by MJDeligan** [comment]
> Is this completed?

Since we "yeeted" the registered part, there isn't really any possibility for a race condition anymore

**Comment by MJDeligan** [comment]
I'll probably make a new issue for caching the profile, so we don't have to refetch every 5 seconds though
