### ISSUE TITLE
Use bottom nav-bar with tabs as main navigation method

### ISSUE THREAD

**Issue by sueszli** [matchyOrg/matchy#24]
Currently we are using a toggleable sidebar for navigation. To improve UX we should relocate the navigation functionality to a bottom nav-bar with tabs. This will facilitate navigation to the most commonly used routes.

Less important routes and other functionality such as switching views and signing out can still reside in the sidebar.

**Comment by sueszli** [comment]
[reminder to myself to update the mockups accordingly]

**Comment by stefnotch** [comment]
https://next.vuetifyjs.com/en/components/bottom-navigation/

**Comment by MJDeligan** [comment]
Maybe we can build on top of [this](https://github.com/matchyOrg/matchy/tree/feat/bottom-nav)

**Comment by stefnotch** [comment]
Done

> Maybe we can build on top of [this](https://github.com/matchyOrg/matchy/tree/feat/bottom-nav)

Thank you, was very helpful :D
