### ISSUE TITLE
Loading state for Event Edit.

### ISSUE THREAD

**Issue by MJDeligan** [matchyOrg/matchy#26]
The EditEvent component needs an Event Object to edit, but on the Edit-Event page we have to fetch the event to update from the server first. This resuts in an awkward delay, from when the page loads to when the event is loaded, because we cannot render the current EditEvent while there is no event to edit.

- **Put a loading state on the entire page (like a spinner) while the event is fetched from the server.**
    - \+ very easy to implement
    - \- not super clear to users what is happening

- ~~**Put a skeleton layout on the page that is shown while the event is not loaded.**~~
    ~~- \+ easy logic, more clear~~
    ~~- \- less maintainable when EditEvent changes,  one time solution for this page only~~
-  ~~**Put a skeleton layout in the EditEvent component and allow undefined event to be passed**~~
    - ~~\+ better maintainability, reusable~~
    - ~~\- requires more effort to handle the event possibly being undefined~~

**Comment by sueszli** [comment]
Lets go with a simple spinner and not overengineer this one ^^
