### ISSUE TITLE
"Create Pairing" page for participants

### ISSUE THREAD

**Issue by sueszli** [matchyOrg/matchy#5]
- [ ] Ability to enter partners email to create a pairing
- [ ] Ability to scan partners QR-code to get their email address
    * https://openbase.com/categories/js/best-javascript-qr-code-generator-libraries
    * https://www.npmjs.com/package/qrcode
- [ ] A timer that shows how much time you have left in that before being forced to decide to like / dislike your partner

**Comment by stefnotch** [comment]
The vue3 QR code library does not use the camera accessing API properly. It only lets you select the first camera in the list.
![image](https://user-images.githubusercontent.com/10220080/191006377-4fc195df-e8a4-47d5-b71e-b3ac3993e533.png)
![image](https://user-images.githubusercontent.com/10220080/191006412-a125f8a5-41c5-4dcc-93a4-184eb5464002.png)

**Comment by sueszli** [comment]
@stefnotch alrighty - this page is done and the QR code stuff have their own issue now ^^
