### ISSUE TITLE
Vercel missing crucial configuration

### ISSUE THREAD

**Issue by MJDeligan** [matchyOrg/matchy#55]
### Problem
Currently only the root route is navigateable from outside the site . When trying to access any route by typing it into the browser Vercel returns a 404. This is because it hasn't been properly configured.

### Reproduce
Visit: [https://matchy.vercel.app/login](https://matchy.vercel.app/login)

See [this thread](https://stackoverflow.com/questions/64815012/why-does-react-router-not-works-at-vercel) for the required configuration.

**Comment by MJDeligan** [comment]
Configured the redirect routes. It's not completely broken now, but we should probably look into possible configurations.

**Comment by sueszli** [comment]
Done yo 👍
