### ISSUE TITLE
Safari support is just bad.

### ISSUE THREAD

**Issue by MJDeligan** [matchyOrg/matchy#56]
### Problem
- Safari support is pretty terrible
    + Unless they had the newest version they couldn't even register for an event because the button was missing
    + Older Safari versions didn't have correct alignment on buttons
    + In a lot of them routing didn't work at all

### Solution
Nothing currently. We'll need to emulate different versions of Safari and check what's going wrong.

**Comment by sueszli** [comment]
Wait @MJDeligan - should we just test safari in a desktop browser or also mobile safari (through xCode emulation because I can't afford an iphone)

**Comment by MJDeligan** [comment]
Mobile emulator would be preferable, since that's what we're targeting.

**Comment by MJDeligan** [comment]
Thinking about it, this might also have been caused by the connection not being https...

**Comment by stefnotch** [comment]
Safari support still seems to be rather broken

**Comment by sueszli** [comment]
(I don't own any apple products anymore ;-;)
